#title: [LampAtTiny]
#description: [documentation for lamp dimmer project]

# Theme
#remote_theme: pages-themes/dinky@v0.2.0
theme:
  name: "material"

#plugins:
# jekyll-remote-theme # add this line to the plugins list if you already have one

#gem "github-pages", group: :jekyll_plugins # for using theme in local in gemfile?

nav:
  - a
  - B: index.md
