site_name: LampATTiny
site_url: https://adrian-tk.github.io/lampattiny/
repo_url: https://github.com/adrian-tk/lampattiny

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-to guides: howtoguides.md
  - References: references.md
  - Explanations: explanations.md
  - History: history.md
  - mkDocs: mkdocs.md

theme:
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format